# Generated by Django 3.2 on 2021-04-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videokarts',
            old_name='manufacturerid',
            new_name='manufacturersid',
        ),
        migrations.AlterUniqueTogether(
            name='videokarts',
            unique_together={('idGPU', 'manufacturersid')},
        ),
    ]
