# Generated by Django 3.2 on 2021-04-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210418_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videokarts',
            unique_together=set(),
        ),
    ]
