# Generated by Django 3.2 on 2021-04-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_videokarts_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='Videokarts',
            new_name='Videokart',
        ),
        migrations.RenameField(
            model_name='videokart',
            old_name='manufacturersid',
            new_name='manufacturerid',
        ),
        migrations.AlterUniqueTogether(
            name='videokart',
            unique_together={('idGPU', 'manufacturerid')},
        ),
    ]
