# Generated by Django 3.2 on 2021-04-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210418_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videokart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videokart',
            name='idGPU',
        ),
        migrations.RemoveField(
            model_name='videokart',
            name='manufacturerid',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Videokart',
        ),
    ]
