# Generated by Django 3.2 on 2021-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_gpu_manufacturer_videokart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videokart',
        ),
    ]
