# Generated by Django 3.2 on 2021-04-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_videokart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videokart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('kolvo', models.IntegerField()),
                ('year', models.DateField()),
                ('info', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('idGPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gpu')),
                ('manufacturerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.manufacturer')),
            ],
            options={
                'unique_together': {('idGPU', 'manufacturerid')},
            },
        ),
    ]
