# Generated by Django 3.2 on 2021-04-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_videokart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videokart',
            name='pub_date',
        ),
    ]
